version: '1'

setup:
  abort_on_failure: true
  dind: true
  image: icr.io/continuous-delivery/pipeline/pipeline-base-image:2.15
  script: |
    #!/usr/bin/env bash
    PIPELINE_DEBUG="$(cat /config/PIPELINE_DEBUG)"
    if [[ "$PIPELINE_DEBUG" == 1 ]]; then
      trap env EXIT
      env
      set -x
    fi
    echo "set up completed"

test:
  abort_on_failure: true
  dind: true
  image: icr.io/continuous-delivery/pipeline/pipeline-base-image:2.15
  script: |
    #!/usr/bin/env bash
    PIPELINE_DEBUG="$(cat /config/PIPELINE_DEBUG)"
    if [[ "$PIPELINE_DEBUG" == 1 ]]; then
      trap env EXIT
      env
      set -x
    fi

deploy:
  abort_on_failure: true
  dind: true
  image: icr.io/continuous-delivery/pipeline/pipeline-base-image:2.15
  script: |
    #!/usr/bin/env bash
    PIPELINE_DEBUG="$(cat /config/PIPELINE_DEBUG)"
    if [[ "$PIPELINE_DEBUG" == 1 ]]; then
      trap env EXIT
      env
      set -x
    fi